stages:
  - build
  - test
  - acceptance

build:
  stage: build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

unit_tests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet restore
    - dotnet test --no-build --verbosity normal

acceptance_tests:
  stage: acceptance
  image: curlimages/curl:latest
  script:
    - endpoints=(
        "http://http://localhost:5028/api/products"
        "http://http://localhost:5028/api/products"
        "http://http://localhost:5028/api/products"
        "http://http://localhost:5028/api/products"
      )
    - |
      for url in "${endpoints[@]}"; do
        echo "Testing $url..."
        http_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
        if [ "$http_code" -ne 200 ]; then
          echo "❌ Error: $url returned status code $http_code"
          exit 1
        else
          echo "✅ $url OK"
        fi
      done

