stages:
  - deploy_backend
  - acceptance_tests   # ← nueva etapa

deploy_backend:
  stage: deploy_backend
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    MYSQL_PORT: 3306
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: DS4_Qatu
    MYSQL_USER: user
    MYSQL_PASSWORD: userpassword
    BACKEND_PORT: 8080

  before_script:
    - apk add --no-cache docker-compose curl
    - echo "Variables cargadas:"
    - env | grep -E 'MYSQL|BACKEND'
  script:
    - docker-compose pull api
    - docker-compose down
    - docker-compose up -d
    - docker ps
    - docker logs backend || true

  when: manual

acceptance_tests:
  stage: acceptance_tests
  image: bash:latest
  dependencies: [deploy_backend]
  before_script:
    - apt-get update && apt-get install -y curl
  script:
    - echo "Esperando a que el backend se inicie..."
    - sleep 10
    - |
      endpoints=(
        "http://localhost:8080/api/products"
      )

      success=true
      for endpoint in "${endpoints[@]}"; do
        echo "Probando $endpoint..."
        http_code=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint")
        if [ "$http_code" -ne 200 ]; then
          echo "❌ Falló: $endpoint (HTTP $http_code)"
          success=false
        else
          echo "✅ OK: $endpoint"
        fi
      done

      if [ "$success" = false ]; then
        echo "❌ Pruebas de aceptación fallidas"
        exit 1
      else
        echo "✅ Todas las pruebas pasaron"
      fi
