stages:
  - deploy_backend

deploy_backend:
  stage: deploy_backend
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache docker-compose
    - ls -la && cat .env 
  script:
    - docker-compose pull backend

    - docker-compose down

    - docker-compose up -d

    - docker ps
    - docker logs backend || true

  when: manual   
