// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qatu.Infrastructure.Persistence;

#nullable disable

namespace Qatu.Infrastructure.Migrations
{
    [DbContext(typeof(QatuDbContext))]
    [Migration("20250602064902_InitialCreatev6")]
    partial class InitialCreatev6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Qatu.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4232),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4239),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4244),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4250),
                            Name = "Home Decor"
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Chats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5632),
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5633),
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71a4d29d-38cc-47a8-b6c1-3306f1000b80"),
                            ChatId = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            Content = "Hi, is the smartphone still in stock?",
                            SenderId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            SentAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5680)
                        },
                        new
                        {
                            Id = new Guid("b3918eec-2072-43fb-8f30-5a5d019080d3"),
                            ChatId = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            Content = "Yes, we have 50 units available!",
                            SenderId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            SentAt = new DateTime(2025, 6, 2, 6, 54, 2, 151, DateTimeKind.Utc).AddTicks(5685)
                        },
                        new
                        {
                            Id = new Guid("fe501d62-3ae4-427b-90d4-91e63ce75e32"),
                            ChatId = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            Content = "Can you tell me more about the laptop?",
                            SenderId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            SentAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5697)
                        },
                        new
                        {
                            Id = new Guid("2ef25744-0d42-4b66-976f-1b06a5a80fb7"),
                            ChatId = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            Content = "It has 16GB RAM and a 1TB SSD.",
                            SenderId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            SentAt = new DateTime(2025, 6, 2, 6, 54, 2, 151, DateTimeKind.Utc).AddTicks(5702)
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5479),
                            Description = "Latest model smartphone",
                            Image = "https://i.ibb.co/xtbmB42y/W-O-X500-Global-4-G-LTE-6-5-Inch-Quad-Core-Big-Battery-Play-Store-Support-Android-Smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699.99m,
                            Rating = 4.5m,
                            Stock = 50,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5487),
                            Description = "High-performance laptop",
                            Image = "https://i.ibb.co/x8BXFDqV/laptop.jpg",
                            Name = "Laptop",
                            Price = 1299.99m,
                            Rating = 4.8m,
                            Stock = 20,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("85c69d14-04ab-4edd-a727-193c0aa364e0"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5498),
                            Description = "Lightweight and portable",
                            Image = "https://i.ibb.co/B2BpfVrx/huawei-matepad-11-5-s-grey.jpg",
                            Name = "Tablet",
                            Price = 499.99m,
                            Rating = 4.3m,
                            Stock = 30,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("2b8f28bc-e742-4fff-929a-9281547058cc"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5508),
                            Description = "Fitness tracker",
                            Image = "https://i.ibb.co/fGrpbQMJ/smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 199.99m,
                            Rating = 4.1m,
                            Stock = 40,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("30a8c927-9774-4057-9f6a-2c4158d2b2d3"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5520),
                            Description = "Noise-canceling headphones",
                            Image = "https://i.ibb.co/4R8qDKD2/hheadphones.jpg",
                            Name = "Headphones",
                            Price = 149.99m,
                            Rating = 4.4m,
                            Stock = 25,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("377f3896-ed4d-4e68-ad30-02cc65e426b8"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5528),
                            Description = "Blue denim jeans",
                            Image = "https://i.ibb.co/0RZTny2w/jeans.jpg",
                            Name = "Jeans",
                            Price = 49.99m,
                            Rating = 4.2m,
                            Stock = 100,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("45726569-0a33-4ed1-9ce3-072324033594"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5535),
                            Description = "100% Cotton T-shirt",
                            Image = "https://i.ibb.co/XZCpMr3Z/tshirt.jpg",
                            Name = "T-Shirt",
                            Price = 19.99m,
                            Rating = 4.0m,
                            Stock = 150,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("73e0fe7b-530b-4cc1-9ad0-a028f116b0a8"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5541),
                            Description = "Waterproof winter jacket",
                            Image = "https://i.ibb.co/9HjpFWPM/jacket.jpg",
                            Name = "Jacket",
                            Price = 99.99m,
                            Rating = 4.3m,
                            Stock = 60,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("7a44753c-aa8c-480f-ade8-bcf20ab8a6ce"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5548),
                            Description = "Comfortable sneakers",
                            Image = "https://i.ibb.co/k2vTgq3j/sneakers.png",
                            Name = "Sneakers",
                            Price = 59.99m,
                            Rating = 4.2m,
                            Stock = 120,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("81461fab-579e-4b88-8406-8c66890f59a3"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5554),
                            Description = "Modern 3-seater sofa",
                            Image = "https://i.ibb.co/ksVP0spL/sofa.jpg",
                            Name = "Sofa",
                            Price = 899.99m,
                            Rating = 4.6m,
                            Stock = 10,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("6acd6f4a-7970-4b83-83ff-439bdde85bce"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5565),
                            Description = "Solid wood dining table",
                            Image = "https://i.ibb.co/hxhd6GTZ/0403037-dallas-ranch-rustic-solid-wood-double-pedestal-dining-table-set.jpg",
                            Name = "Dining Table",
                            Price = 499.99m,
                            Rating = 4.5m,
                            Stock = 15,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("580eb52d-ade2-4ace-b63d-d905c97d2bd4"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5576),
                            Description = "Queen size bed frame",
                            Image = "https://i.ibb.co/84xwsfWB/bed.jpg",
                            Name = "Bed Frame",
                            Price = 299.99m,
                            Rating = 4.7m,
                            Stock = 5,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("fef516da-eb8e-4798-8d01-17750eeb8a03"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5592),
                            Description = "LED floor lamp",
                            Image = "https://i.ibb.co/bMHCSV6p/led.png",
                            Name = "Lamp",
                            Price = 49.99m,
                            Rating = 4.2m,
                            Stock = 30,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("21e26ed0-51e9-44ec-add9-5143a50438d1"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5603),
                            Description = "Soft area rug",
                            Image = "https://i.ibb.co/SWjnYY1/81-Ry-C8-YEst-L-AC-SL1500.jpg",
                            Name = "Carpet",
                            Price = 99.99m,
                            Rating = 4.3m,
                            Stock = 20,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5434),
                            Description = "Admin verification request",
                            Status = 0,
                            StoreDescription = "Store managed by admin",
                            StoreName = "Admin Store",
                            UserId = new Guid("44147d07-ae1c-45ae-af1c-984ff4d49eba")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5441),
                            Description = "Request to update store info",
                            Status = 0,
                            StoreDescription = "Electronics and gadgets",
                            StoreName = "SuperElectro",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5447),
                            Description = "Support needed for order issue",
                            Status = 0,
                            StoreDescription = "Store created for buyer support request",
                            StoreName = "Temporary Buyer Store",
                            UserId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-bcde-f23456789012"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            ChatId = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5653),
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-d8e9-0123-def0-456789012345"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            ChatId = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(5655),
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4193),
                            Description = "Electronics and gadgets",
                            Name = "Tech Store",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4200),
                            Description = "Clothing and accessories",
                            Name = "Fashion Store",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4205),
                            Description = "Home essentials and furniture",
                            Name = "Home Store",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44147d07-ae1c-45ae-af1c-984ff4d49eba"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4045),
                            Email = "admin@qatu.com",
                            Name = "Admin User",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4053),
                            Email = "seller@qatu.com",
                            Name = "Seller User",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            CreatedAt = new DateTime(2025, 6, 2, 6, 49, 2, 151, DateTimeKind.Utc).AddTicks(4059),
                            Email = "buyer@qatu.com",
                            Name = "Buyer User",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Category", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Chat", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Message", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Product", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Request", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Qatu.Domain.Entities.Request", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Chat", "Chat")
                        .WithOne("Sale")
                        .HasForeignKey("Qatu.Domain.Entities.Sale", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Chat");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Store", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "User")
                        .WithMany("Stores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Sale")
                        .IsRequired();
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.User", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
