// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qatu.Infrastructure.Persistence;

#nullable disable

namespace Qatu.Infrastructure.Migrations
{
    [DbContext(typeof(QatuDbContext))]
    [Migration("20250601221205_InitialCreatev5")]
    partial class InitialCreatev5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Qatu.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4467),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4473),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4479),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4484),
                            Name = "Home Decor"
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Chats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5855),
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5856),
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c731501-1703-4a70-8292-be09395bb0b4"),
                            ChatId = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            Content = "Hi, is the smartphone still in stock?",
                            SenderId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            SentAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5908)
                        },
                        new
                        {
                            Id = new Guid("fd1cfa8f-bd98-4113-803c-40cf9b2a778c"),
                            ChatId = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            Content = "Yes, we have 50 units available!",
                            SenderId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            SentAt = new DateTime(2025, 6, 1, 22, 17, 4, 917, DateTimeKind.Utc).AddTicks(5914)
                        },
                        new
                        {
                            Id = new Guid("b9c97e45-02b9-4564-a57b-04f82994f2cd"),
                            ChatId = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            Content = "Can you tell me more about the laptop?",
                            SenderId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            SentAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5924)
                        },
                        new
                        {
                            Id = new Guid("84b36fca-7960-428f-8786-f58194847b16"),
                            ChatId = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            Content = "It has 16GB RAM and a 1TB SSD.",
                            SenderId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            SentAt = new DateTime(2025, 6, 1, 22, 17, 4, 917, DateTimeKind.Utc).AddTicks(5929)
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5626),
                            Description = "Latest model smartphone",
                            Name = "Smartphone",
                            Price = 699.99m,
                            Rating = 4.5m,
                            Stock = 50,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5633),
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 1299.99m,
                            Rating = 4.8m,
                            Stock = 20,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("71235749-f6df-49ea-a971-0e649c105de3"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5645),
                            Description = "Lightweight and portable",
                            Name = "Tablet",
                            Price = 499.99m,
                            Rating = 4.3m,
                            Stock = 30,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("97d965d3-40d9-45c2-87a2-2f90a260624f"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5657),
                            Description = "Fitness tracker",
                            Name = "Smartwatch",
                            Price = 199.99m,
                            Rating = 4.1m,
                            Stock = 40,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("30a8c927-9774-4057-9f6a-2c4158d2b2d3"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5666),
                            Description = "Noise-canceling headphones",
                            Name = "Headphones",
                            Price = 149.99m,
                            Rating = 4.4m,
                            Stock = 25,
                            StoreId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("377f3896-ed4d-4e68-ad30-02cc65e426b8"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5674),
                            Description = "Blue denim jeans",
                            Name = "Jeans",
                            Price = 49.99m,
                            Rating = 4.2m,
                            Stock = 100,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("45726569-0a33-4ed1-9ce3-072324033594"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5681),
                            Description = "100% Cotton T-shirt",
                            Name = "T-Shirt",
                            Price = 19.99m,
                            Rating = 4.0m,
                            Stock = 150,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("73e0fe7b-530b-4cc1-9ad0-a028f116b0a8"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5688),
                            Description = "Waterproof winter jacket",
                            Name = "Jacket",
                            Price = 99.99m,
                            Rating = 4.3m,
                            Stock = 60,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("7a44753c-aa8c-480f-ade8-bcf20ab8a6ce"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5695),
                            Description = "Comfortable sneakers",
                            Name = "Sneakers",
                            Price = 59.99m,
                            Rating = 4.2m,
                            Stock = 120,
                            StoreId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("81461fab-579e-4b88-8406-8c66890f59a3"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5727),
                            Description = "Modern 3-seater sofa",
                            Name = "Sofa",
                            Price = 899.99m,
                            Rating = 4.6m,
                            Stock = 10,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("9af720fb-d9ae-40e2-8d97-33f8f6c16f93"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5791),
                            Description = "Solid wood dining table",
                            Name = "Dining Table",
                            Price = 499.99m,
                            Rating = 4.5m,
                            Stock = 15,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("5839e0fc-3ad9-4c39-b462-edcf1dcb77b5"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5801),
                            Description = "Queen size bed frame",
                            Name = "Bed Frame",
                            Price = 299.99m,
                            Rating = 4.7m,
                            Stock = 5,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("86fedf8b-d698-4100-b320-77ece7f4fe04"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5814),
                            Description = "LED floor lamp",
                            Name = "Lamp",
                            Price = 49.99m,
                            Rating = 4.2m,
                            Stock = 30,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("2bc6c904-02a4-4af9-ac4d-f2b19248a9cf"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5824),
                            Description = "Soft area rug",
                            Name = "Carpet",
                            Price = 99.99m,
                            Rating = 4.3m,
                            Stock = 20,
                            StoreId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5576),
                            Description = "Admin verification request",
                            Status = 0,
                            StoreDescription = "Store managed by admin",
                            StoreName = "Admin Store",
                            UserId = new Guid("44147d07-ae1c-45ae-af1c-984ff4d49eba")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5583),
                            Description = "Request to update store info",
                            Status = 0,
                            StoreDescription = "Electronics and gadgets",
                            StoreName = "SuperElectro",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5590),
                            Description = "Support needed for order issue",
                            Status = 0,
                            StoreDescription = "Store created for buyer support request",
                            StoreName = "Temporary Buyer Store",
                            UserId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-bcde-f23456789012"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            ChatId = new Guid("c1d2e3f4-a5b6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5881),
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-d8e9-0123-def0-456789012345"),
                            BuyerId = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            ChatId = new Guid("e3f4a5b6-c7d8-9012-cdef-345678901234"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(5882),
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            SellerId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4427),
                            Description = "Electronics and gadgets",
                            Name = "Tech Store",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4433),
                            Description = "Clothing and accessories",
                            Name = "Fashion Store",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4439),
                            Description = "Home essentials and furniture",
                            Name = "Home Store",
                            UserId = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869")
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44147d07-ae1c-45ae-af1c-984ff4d49eba"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4048),
                            Email = "admin@qatu.com",
                            Name = "Admin User",
                            Password = "password123",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("a89bff1d-2db6-4e9e-8fd2-bf3ee3ed8869"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4062),
                            Email = "seller@qatu.com",
                            Name = "Seller User",
                            Password = "password123",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("87b84069-9bda-4b44-8d0d-d52c3a8bbc74"),
                            CreatedAt = new DateTime(2025, 6, 1, 22, 12, 4, 917, DateTimeKind.Utc).AddTicks(4068),
                            Email = "buyer@qatu.com",
                            Name = "Buyer User",
                            Password = "password123",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Category", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Chat", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Message", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Product", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Request", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Qatu.Domain.Entities.Request", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Chat", "Chat")
                        .WithOne("Sale")
                        .HasForeignKey("Qatu.Domain.Entities.Sale", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qatu.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Chat");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Store", b =>
                {
                    b.HasOne("Qatu.Domain.Entities.User", "User")
                        .WithMany("Stores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Sale")
                        .IsRequired();
                });

            modelBuilder.Entity("Qatu.Domain.Entities.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Qatu.Domain.Entities.User", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
