@baseUrl = http://localhost:5028/api
@products = /products

POST  {{baseUrl}}{{products}}
Accept: application/json
Content-Type: application/json

{
  "StoreId": 1,
  "Name": "toy box",
  "Description": "Toy box for children aged 9 to 10.",
  "Category": "toys for children",
  "Price": 11,
  "Stock": 7
}

###

POST {{baseUrl}}{{products}}/bulk
Accept: application/json
Content-Type: application/json

{
  "products": [
    {
      "storeId": 1,
      "name": "Lego Creator",
      "description": "Building toy set",
      "category": "Toys",
      "price": 29.99,
      "stock": 15
    },
    {
      "storeId": 1,
      "name": "Color Pencils Pack",
      "description": "Pack of 24 colored pencils",
      "category": "Stationery",
      "price": 5.49
    },
    {
      "storeId": 1,
      "name": "RC Car",
      "category": "Electronics",
      "price": 45.00,
      "stock": 10
    }
  ]
}

###