@baseUrl = http://localhost:5028/api
@products = /products
@IDproduct = /d9112846-d97d-4395-8e37-f855759aa650

@stores = /stores

@IDstore = /44444444-4444-4444-4444-444444444444

GET  {{baseUrl}}{{products}}

### 
GET {{baseUrl}}{{products}}{{IDproduct}}

###
PUT {{baseUrl}}{{products}}{{IDproduct}}
Accept: application/json
Content-Type: application/json

{
  "storeId": "44444444-4444-4444-4444-444444444444",
  "name": "Nuevo Producto 2",
  "description": "Descripción actualizada",
  "category": "Tecnología",
  "price": 199.99
}


###
POST  {{baseUrl}}{{products}}
Accept: application/json
Content-Type: application/json

{
  "StoreId": "44444444-4444-4444-4444-444444444444",
  "Name": "toy box",
  "Description": "Toy box for children aged 9 to 10.",
  "Category": "toys for children",
  "Price": 11,
  "Stock": 7
}

###

POST {{baseUrl}}{{products}}/bulk
Accept: application/json
Content-Type: application/json

{
  "products": [
    {
      "storeId": "44444444-4444-4444-4444-444444444444",
      "name": "Lego Creator",
      "description": "Building toy set",
      "category": "Toys",
      "price": 29.99,
      "stock": 15
    },
    {
      "storeId": "44444444-4444-4444-4444-444444444444",
      "name": "Color Pencils Pack",
      "description": "Pack of 24 colored pencils",
      "category": "Stationery",
      "price": 5.49,
      "stock": 10
    },
    {
      "storeId": "44444444-4444-4444-4444-444444444444",
      "name": "RC Car",
      "description": "Pack of 24 colored pencils",
      "category": "Electronics",
      "price": 45.00,
      "stock": 10
    }
  ]
}

###
DELETE {{baseUrl}}{{products}}{{IDproduct}}


## Store

###
GET {{baseUrl}}{{stores}}{{IDstore}}

###
POST {{baseUrl}}{{stores}}
Accept: application/json
Content-Type: application/json

{
  "UserId": "22222222-2222-2222-2222-222222222222",
  "Name": "toy box",
  "Description": "Toy box for children aged 9 to 10."
}

###
PUT {{baseUrl}}{{stores}}{{IDstore}}
Accept: application/json
Content-Type: application/json

{
  "Name": "toy box 333",
  "Description": "Toy box for adult aged 9 to 10."
}


###
DELETE {{baseUrl}}{{stores}}/66666666-6666-6666-6666-666666666666


###
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImhhcExyZndkNkNXdkI5RUJvd3I3XyJ9.eyJodHRwczovL3FhdHUuYXBpL3V1aWQiOiJlYjRmYmYyOS1lZGU2LTRlNWItODQyMi03ZTYxMzM5NGNjYjIiLCJodHRwczovL3FhdHUuYXBpL3JvbGVzIjpbIlVzZXIiXSwiaXNzIjoiaHR0cHM6Ly9kZXYtYTh5Mzh0czBqaTB6eG9kMy51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTgwNDAyNDI2NDYyNTMyMDIyOTEiLCJhdWQiOlsiaHR0cHM6Ly9xYXR1LmFwaSIsImh0dHBzOi8vZGV2LWE4eTM4dHMwamkwenhvZDMudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTc0Nzg4OTM5OCwiZXhwIjoxNzQ3OTc1Nzk4LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiUmd2TjV6ZHVnTlZVaVZ4alN1djFwN2g3UjdUeXpieHoifQ.gFDtFL5sYKeAHooDAZE7YO1SJKbzZdnqGg3SuY5tYM5iKU8AJEEYPmWOCoCVHUXvjLzRBTmy2PDxN1iReKW9-CPmP8U4N-2GjjebFnMZDmhiKvtO3XnnfDO1xi9ezw6BO5GVK4Weqi1oqwpbuY3cPg_bf1Ys6jKmegrBQxJU8gsSRBVT9BZBxAErQhZkUFcR2_Y-DR8MKWLEg0zSDEQEEc2WhNtiY_yuWLt9-Uh_jbSsW30SNF2lnZe7LZq0NF6J_iCGEDE0tvKSTdP3wabcrlY8-BQzEwCJ9rM9Y8H8I38n1AqQcMl6hX_ZeuzcsMbDnIRJtNsVaDXMQQtpIDzmbg
GET {{baseUrl}}/categories/a9c054c4-9101-4d57-b848-b42fad78afb1