@baseUrl = http://localhost:5028/api
@products = /products

POST  {{baseUrl}}{{products}}
Accept: application/json
Content-Type: application/json

{
  "StoreId": 1,
  "Name": "toy box",
  "Description": "Toy box for children aged 9 to 10.",
  "Category": "toys for children",
  "Price": 11,
  "Stock": 7
}

###
